# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 21:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20171009_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='org_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.Organization'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='item_desc',
            field=models.TextField(max_length=200, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(max_length=200, verbose_name='Name of Item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_uni_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='org_item_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='location',
            name='loc_name',
            field=models.CharField(max_length=200, verbose_name='Name of Location'),
        ),
    ]
