# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 09:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_uni_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular item across whole organization', primary_key=True, serialize=False)),
                ('item_name', models.CharField(help_text='Name of item', max_length=200, verbose_name='Name of Item')),
                ('org_item_id', models.CharField(blank=True, help_text='Enter Item ID No. / Serial No. or leave blank if none ', max_length=200)),
                ('item_desc', models.TextField(help_text='Description of the item', max_length=200, verbose_name='Description')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc_name', models.CharField(help_text='Name of location in organization', max_length=200, verbose_name='Name of Location')),
                ('loc_desc', models.TextField(max_length=1000, verbose_name='Description')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=200, verbose_name='Name of Organization')),
                ('service', models.TextField(help_text='Enter the list of services your organization provides', max_length=1000)),
                ('address', models.TextField(help_text='Street and City')),
                ('state', models.CharField(help_text='Enter state', max_length=75)),
                ('email', models.EmailField(max_length=75)),
                ('website', models.URLField(blank=True)),
                ('tel', models.IntegerField(help_text='Enter telephone number')),
                ('slug', models.SlugField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['org_name'],
            },
        ),
        migrations.AddField(
            model_name='location',
            name='org_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Organization'),
        ),
        migrations.AddField(
            model_name='item',
            name='loc_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Location'),
        ),
    ]
