# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='timestamp',
        ),
        migrations.AlterField(
            model_name='organization',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='organization',
            name='service',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='organization',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='state',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='organization',
            name='tel',
            field=models.IntegerField(),
        ),
    ]
