# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20171009_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='organization',
            name='service',
            field=models.TextField(max_length=200),
        ),
    ]
