# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20171009_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_uni_id',
        ),
        migrations.AddField(
            model_name='item',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
