# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 09:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_remove_item_org_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='last_accessed',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='org_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.Organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='last_accessed',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 12, 9, 38, 32, 831144, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='last_accessed',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 12, 9, 38, 44, 463319, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
