# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20171012_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='last_accessed',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='service',
            field=models.CharField(max_length=200),
        ),
    ]
